### ISSUE TITLE
Broken link to the documentation of AbstractFFTs in docs

### ISSUE THREAD

**Issue by jishnub** [JuliaMath/FFTW.jl#101]
Currently the link in `docs/src/fft.md` points to https://juliamath.github.io/AbstractFFTs.jl/stable/api.html, however the link appears to have moved to https://juliamath.github.io/AbstractFFTs.jl/stable/api/

**Comment by giordano** [comment]
This sounds like a good opportunity to open a quick and simple pull request 😉
