### ISSUE TITLE
Broken precompilation under Julia 1.3-alpha1/win64

### ISSUE THREAD

**Issue by henry-eshbaugh** [JuliaMath/FFTW.jl#110]
Hi all,

FFTW precompilation when directly imported breaks once, then seems OK (I have replicated this a few times with different Julia instances). It seems that the DLL libfftw3-3.dll does not export `fftw_threads_set_callback()` which is required for the new PARTR scheduling scheme under 1.3. Curious if the DLL needs updating or I'm just pulling a wonky one from the build script.

```
julia> using FFTW
ERROR: InitError: ccall: could not find function fftw_threads_set_callback in library C:\Users\henry\.julia\packages\FFTW\xi4tZ\deps\usr\bin\libfftw3-3.dll
Stacktrace:
 [1] __init__() at C:\Users\henry\.julia\packages\FFTW\xi4tZ\src\FFTW.jl:60
 [2] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:692
 [3] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:776
 [4] _require(::Base.PkgId) at .\loading.jl:1001
 [5] require(::Base.PkgId) at .\loading.jl:922
 [6] require(::Module, ::Symbol) at .\loading.jl:917
during initialization of module FFTW

julia> using FFTW

julia> fft([1 -1])
1×2 Array{Complex{Float64},2}:
 0.0+0.0im  2.0+0.0im
```

Repeating "using" until the library imports does not seem to work in the context of other libraries (e.g. DSP.jl, Wavelets.jl):

```
julia> using DSP
[ Info: Precompiling DSP [717857b8-e6f2-59f4-9121-6e50c889abd2]
ERROR: LoadError: InitError: ccall: could not find function fftw_threads_set_callback in library C:\Users\henry\.julia\packages\FFTW\xi4tZ\deps\usr\bin\libfftw3-3.dll
Stacktrace:
 [1] __init__() at C:\Users\henry\.julia\packages\FFTW\xi4tZ\src\FFTW.jl:60
 [2] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:692
 [3] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:776
 [4] _require(::Base.PkgId) at .\loading.jl:1001
 [5] require(::Base.PkgId) at .\loading.jl:922
 [6] require(::Module, ::Symbol) at .\loading.jl:917
 [7] include at .\boot.jl:328 [inlined]
 [8] include_relative(::Module, ::String) at .\loading.jl:1105
 [9] include(::Module, ::String) at .\Base.jl:31
 [10] top-level scope at none:2
 [11] eval at .\boot.jl:330 [inlined]
 [12] eval(::Expr) at .\client.jl:433
 [13] top-level scope at .\none:3
during initialization of module FFTW
in expression starting at C:\Users\henry\.julia\packages\DSP\wwKNu\src\DSP.jl:3
ERROR: Failed to precompile DSP [717857b8-e6f2-59f4-9121-6e50c889abd2] to C:\Users\henry\.julia\compiled\v1.3\DSP\OtML7_PQCoN.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1274
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
```

The library lives here:
```
julia> pathof(FFTW)
"C:\\Users\\henry\\.julia\\packages\\FFTW\\xi4tZ\\src\\FFTW.jl"
```

Finally, version info:
```

julia> versioninfo()
Julia Version 1.3.0-rc1.0
Commit 768b25f6a8 (2019-08-18 00:04 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, sandybridge)
Environment:
  JULIA_NUM_THREADS = 8
```

Help would be appreciated :). Do I just need updated DLLs?

**Comment by giordano** [comment]
> Though CI is passing on Windows nightly for FFTW.jl

Yes, that's why I suspect for some reasons the OP is not using the correct library version and wanted to double check that.

**Comment by henry-eshbaugh** [comment]
Hi all,

Many thanks again!

```
julia> using Libdl, FFTW

julia> Libdl.dlsym(Libdl.dlopen(FFTW.libfftw3), :fftw_threads_set_callback)
ERROR: could not load symbol "fftw_threads_set_callback":
The specified procedure could not be found.

Stacktrace:
 [1] dlsym(::Ptr{Nothing}, ::Symbol) at C:\cygwin\home\henry\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Libdl\src\Libdl.jl:56
 [2] top-level scope at none:1

julia> FFTW.libfftw3
"C:\\Users\\henry\\.julia\\dev\\FFTW\\deps\\usr\\bin\\libfftw3-3.dll"
```

I'll pull the DLLs from the nightly and see if a fix is had on my box, stay tuned!

**Comment by giordano** [comment]
Wait, you said that your package is in
```julia
julia> pathof(FFTW)
"C:\\Users\\henry\\.julia\\packages\\FFTW\\xi4tZ\\src\\FFTW.jl"
```
but the library is in another place:
```julia
julia> FFTW.libfftw3
"C:\\Users\\henry\\.julia\\dev\\FFTW\\deps\\usr\\bin\\libfftw3-3.dll"
```
You have something mixed up

**Comment by giordano** [comment]
My guess is that should work:
```julia
Libdl.dlsym(Libdl.dlopen("C:\\Users\\henry\\.julia\\packages\\FFTW\\xi4tZ\\deps\\usr\\bin\\libfftw3-3.dll"), :fftw_threads_set_callback)
```

**Comment by henry-eshbaugh** [comment]
Newbie to Julia, do alpha releases hide the packages you install in the \dev path? Could explain the mismatch in paths; I've not tried to do anything outrageously funky :).

> 
> 
> My guess is that this should work for you:
> 
> ```julia
> Libdl.dlsym(Libdl.dlopen("C:\\Users\\henry\\.julia\\packages\\FFTW\\xi4tZ\\deps\\usr\\bin\\libfftw3-3.dll"), :fftw_threads_set_callback)
> ```

Unfortunately, again no dice :(.
```

julia> Libdl.dlsym(Libdl.dlopen("C:\\Users\\henry\\.julia\\packages\\FFTW\\xi4tZ\\deps\\usr\\bin\\libfftw3-3.dll"), :fftw_threads_set_callback)
ERROR: could not load symbol "fftw_threads_set_callback":
The specified procedure could not be found.

Stacktrace:
 [1] dlsym(::Ptr{Nothing}, ::Symbol) at C:\cygwin\home\henry\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Libdl\src\Libdl.jl:56
 [2] top-level scope at none:1
```
Could you link me those DLLs more directly? I can move them in by hand to see if the problem is mitigated in this build.

**Comment by giordano** [comment]
I'd recommend to remove FFTW in Julia:
```
]rm FFTW
```
and manually remove the directory in `"C:\Users\henry\.julia\dev\FFTW"` (unless you have particular reason to keep the repository on your computer).

Then, restart Julia and reinstall FFTW:
```
]add FFTW
build FFTW
```
(note: both commands must be run in the Pkg manager mode, I put the opening `]` only once).  Now in the Julia prompt you should hopefully be able to do
```
using FFTW
```

**Comment by giordano** [comment]
If this is still failing let's check that you got the right library:

* I expect `FFTW.libfftw3` to be:
    ```
    "C:\\Users\\henry\\.julia\\packages\\FFTW\\xi4tZ\\deps\\usr\\bin\\libfftw3-3.dll"
    ```
* check the SHA256 hash of the library.  You can do this within Julia with the package `SHA`:
    ```julia
    julia> using SHA, FFTW

    julia> bytes2hex(open(FFTW.libfftw3) do f; sha2_256(f); end)
    "af1c862f036b3d302e837a1725dc7fba596ace3b00522091cbaeca5b6d6deebe"
    ```

If you get different results, you either still have something wrong or I miscomputed the hash (:see_no_evil:)

**Comment by henry-eshbaugh** [comment]
Deleted the `dev` path after removing FFTW, then did `add` and `build`. Again, no success, though `FFTW.libfftw3` ponts in the right direction:

```Julia
julia> using FFTW
julia> FFTW.libfftw3
"C:\\Users\\henry\\.julia\\packages\\FFTW\\xi4tZ\\deps\\usr\\bin\\libfftw3-3.dll"
```

Very unfortunately:

```
julia> using SHA
julia> bytes2hex(open(FFTW.libfftw3) do f; sha2_256(f); end)
"af1c862f036b3d302e837a1725dc7fba596ace3b00522091cbaeca5b6d6deebe"
```

**Comment by stevengj** [comment]
> Though CI is passing on Windows nightly for FFTW.jl

Ah, but I just realized that AppVeyor does not exercise this feature — only the Travis script (which is currently just for linux and osx) tries setting `JULIA_NUM_THREADS=2`

**Comment by henry-eshbaugh** [comment]
That's promising; does that mean there's simply a missing `_declspec`?

**Comment by stevengj** [comment]
Yes.

**Comment by stevengj** [comment]
I updated the FFTW source code at https://github.com/FFTW/fftw3/commit/8a9236c494f680e550c536eeb6aa7102ecfad2ca … now we need a new build.

**Comment by stevengj** [comment]
Should be fixed on the master branch now, if you can try that (`pkg> dev FFTW`) and confirm it would be appreciated.

**Comment by henry-eshbaugh** [comment]
Happy to report all OK! Thanks so much!
