### ISSUE TITLE
JULIA_NUM_THREADS not working with 1.3-rc2

### ISSUE THREAD

**Issue by feanor12** [JuliaMath/FFTW.jl#113]
I had problems with PGFPlots in Julia 1.3-rc2 and it seems FFTW caused it. 

Issue showing the problem: JuliaTeX/PGFPlots.jl#126 

1. Install julia 1.3-rc2
2. `add Plots PGFPlots`
3. `ENV["JULIA_NUM_THREADS"]=4`
4. `using Plots`
5. `pgfplots()`

**Comment by stevengj** [comment]
Duplicate of #110.  Should be fixed in FFTW master.
