### ISSUE TITLE
Pkg.add("FFTW") shouldn't install MKL

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMath/FFTW.jl#133]
Since https://github.com/JuliaMath/FFTW.jl/commit/8a9197a08890ca18b3aeb8bdff568087026778d8, `]add FFTW` installs MKL. I'm not a free software absolutist, but I don't think adding such a core package (that used to be part of base) should download a non-free binary dependency. A much more practical concern is that MKL is a whopping 130mb, and my work connection sucks...

**Comment by ararslan** [comment]
I definitely agree, but this is a difficult problem to address at the moment, since there is no support in the package manager for conditional dependencies.

**Comment by antoine-levitt** [comment]
Given that seems to be still some time away, perhaps reverting to the previous state would be best? Even with a good connection the download still takes quite a bit of time (during which it is unclear what's happening)

**Comment by ararslan** [comment]
The previous state was having MKL managed by Conda, which introduces a Python dependency. It sort of seems like there are no good options at the moment...

**Comment by antoine-levitt** [comment]
I know very little about these things (and am eternally grateful to the poor souls that have to manage this) so sorry if I'm missing something, but isn't depending on python way better than depending on MKL? It's free software, it's more lightweight, it's shared by more packages, it runs on all sane platforms, and it's installed on most machines already.

**Comment by Keno** [comment]
> isn't depending on python way better than depending on MKL

It was using Python to install MKL

**Comment by antoine-levitt** [comment]
Not by default though? It's definitely the first time I've noticed `]add FFTW` downloads 130mb.

**Comment by stevengj** [comment]
Previously it only installed Conda etcetera if FFTW.jl was configured to use MKL.  Now, because Pkg doesn't support optional dependencies, we must unconditionally download MKL_jll.

**Comment by antoine-levitt** [comment]
So why not switch back to the old system until Pkg supports optional dependencies?

**Comment by xgdgsc** [comment]
Please revert this. You are making my life with a bad network and AMD processors very hard.

**Comment by KristofferC** [comment]
The artifact system already supports "lazy artifacts" that are only downloaded when the artifact is actually used.

**Comment by giordano** [comment]
With latest release of `MKL_jll`, `v2019.0.117+2` (don't dare to install `v2019.0.117+1`, make sure to update the registry) the tarball of `MKL_jll` is not downloaded upon just installing the package, but only when doing `using MKL_jll`.

In the context of `FFTW.jl`, this means that the tarball is never downloaded unless you had set `JULIA_FFTW_PROVIDER` to `MKL`.  This should effectively fix the issue, so I'm going to close the ticket.

**Comment by c42f** [comment]
Thank you Mosè, that's excellent!
