### ISSUE TITLE
Five argument mul!

### ISSUE THREAD

**Issue by ranocha** [JuliaMath/FFTW.jl#139]
I couldn't find a 5 argument method of `mul!` in [FFTW.jl](https://github.com/JuliaMath/FFTW.jl) for `FFTW.rFFTWPlan` and its siblings. Would it be reasonable to add such methods? In particular, I would like to be able to do something like
```julia
julia> using LinearAlgebra, FFTW

julia> x = Vector(range(0., 1., length=16));

julia> rfft_plan = plan_rfft(x);

julia> y = rfft_plan * x; y .= 1;

julia> mul!(y, rfft_plan, x);

julia> mul!(y, rfft_plan, x, 1.0, 0.5) # this yields a MethodError
```

Note: I've asked this question on [discourse](https://discourse.julialang.org/t/five-argument-mul-in-fftw/35443).

**Comment by stevengj** [comment]
FFTW doesn't support this operation, so there is nothing we could implement here that would be faster than just doing the scaling etcetera yourself.

**Comment by ranocha** [comment]
Okay, thanks.
