### ISSUE TITLE
libfftw3 not defined on Raspberry Pi 3 Raspbian

### ISSUE THREAD

**Issue by amckay1** [JuliaMath/FFTW.jl#143]
Hi, I'm using Julia 1.3.1 32-bit generic binary on an Arm-based Raspberry Pi and was trying to install Images.jl but kept running into a "libfftw3 not defined" error that I traced to FFTW.jl (v1.2.0). I've installed 'libfftw3-dev' and I think I can get the library to load using Libdl, but realized that is likely not the problem since it is simply not defined in the 'src/FFTW.jl' file somehow? Looking at 'src/FFTW.jl' (and following the error message) I realized line 27 does not make it clear where libfftw3 is coming from, so I'm guessing one of packages used should be pulling it in but isn't. 

Thanks for any help you can provide and I understand that since this is an Arm architecture the answer might be "that just doesn't work right now" :)

**Comment by giordano** [comment]
What version of `FFTW.jl` are you using?

**Comment by amckay1** [comment]
v1.2.0. Thanks!

**Comment by giordano** [comment]
Can you please try to do
```julia
using Pkg
Pkg.add(PackageSpec(name="FFTW_jll", rev="704f8580a0c9395721016c85a9ea376e272074fe"))
```
and see if now `FFTW.jl` works for you?

**Comment by amckay1** [comment]
Thanks for the suggestion, unfortunately it doesn't seem to work. I now have `FFTW_jll v3.3.9+4 #704f858` but running `using FFTW` results in the same error, same for when I remove and add FFTW.jl back or build it again.

**Comment by giordano** [comment]
That's because I told you the wrong revision :woman_facepalming:   Try this:
```julia
using Pkg
Pkg.add(PackageSpec(name="FFTW_jll", rev="633945700554833c7ecc7140bf2e76c4e37cc8e5"))
```

**Comment by amckay1** [comment]
Haha, second times a charm, I think that one did the trick! I had to restart Julia but now I can load FFTW.jl and Images.jl as well!  Thank you so much!
