### ISSUE TITLE
Building fails on julia 0.6

### ISSUE THREAD

**Issue by eford** [JuliaMath/FFTW.jl#15]
julia> Pkg.build("FFTW")
INFO: Building FFTW
================================================================[ ERROR: FFTW ]================================================================

LoadError: Provider BinDeps.PackageManager failed to satisfy dependency libfftw3_threads
while loading /astro/faculty/ebf11/.julia/v0.6/FFTW/deps/build.jl, in expression starting on line 73

===============================================================================================================================================

===============================================================[ BUILD ERRORS ]================================================================

WARNING: FFTW had build errors.

 - packages with build errors remain installed in /astro/faculty/ebf11/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("FFTW")`
 - build a single package by running its `deps/build.jl` script

===============================================================================================================================================

**Comment by ararslan** [comment]
Please post the output of `versioninfo()` and `Pkg.status("FFTW")`

**Comment by eford** [comment]
julia> versioninfo()
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)

julia> Pkg.status("FFTW")
 - FFTW                          0.0.2

FWIW, I do have fftw already installed, so there may be a way to point julia to that version.  But I presume that you want it to be able to install it's own version of fftw to maximize ease of  use.
> sudo yum install fftw
>...
Package fftw-3.2.1-3.1.el6.x86_64 already installed and latest version
Nothing to do

**Comment by ararslan** [comment]
Ah, I don't have a system with Yum to test, but I think I see what the problem is: Yum is installing `libfftw3_threads.so.3`, which because of the versioned `so` is not being recognized as an alias for the desired library. Fix incoming.

**Comment by ararslan** [comment]
Soon it won't be necessary to build FFTW on Julia 0.6, just FYI. Still working on that though.

**Comment by ararslan** [comment]
The package no longer requires building on 0.6.
