### ISSUE TITLE
timing freeze in 1.5 

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaMath/FFTW.jl#152]
I notice a bug when timing tests. It seems specific to FFTW, so I report it here. If I do `using Pkg; @time Pkg.test("FFTW")` then the first run works fine. 

Second time, freezes. Doesn't seem an issue for other packages, or on 1.4, or for testing without `@time`.

```julia
julia> versioninfo()
Julia Version 1.5.0-beta1.0
Commit 6443f6c95a (2020-05-28 17:42 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by giordano** [comment]
Does it happen also when running the tests with a single Julia thread?  I'm also experiencing some deadlocks with the latest stable version.  Can you try again with the `master` version, which includes #151?

**Comment by AshtonSBradley** [comment]
thanks for this, fixed on master

**Comment by giordano** [comment]
Ok, I'm closing this issue.  The deadlock is probably the same as #141, but setting the number of FFTW threads to 1 as in #151 should circumvent it
