### ISSUE TITLE
size should return 2 arguments?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMath/FFTW.jl#159]
This is a bit counter intuitive:
```julia
julia> plan_fft(randn(5)) |> size
(5,)

julia> plan_fft(randn(5)) |> length
5
```
because the FFT plans behave like matrices. So I would have expected
```julia
julia> plan_fft(randn(5)) |> size
(5,5)

julia> plan_fft(randn(5)) |> length
25
```

**Comment by stevengj** [comment]
Seems like it?  Note that it's not defined in this package, though.  It's defined here: https://github.com/JuliaMath/AbstractFFTs.jl/blob/9372553601625899d0fd21830894a8f043eaf211/src/definitions.jl#L13-L14
