### ISSUE TITLE
Concurrency bugs in the latest release

### ISSUE THREAD

**Issue by Octogonapus** [JuliaMath/FFTW.jl#161]
With the release of v1.2.3, I am now seeing a lot of these errors:
```
error in running finalizer: ErrorException("task switch not allowed from inside gc finalizer")
error in running finalizer: ErrorException("val already in a list")
```

We use FFTW on multiple threads. Is this a supported use case?

I would have liked to attach a small example to reproduce the problem, but I can't figure one out. Maybe it would help if others commented with ideas on how these errors could happen.

**Comment by stevengj** [comment]
No, this was not intentional.  We were trying to fix a deadlock in the finalizers in #160, and apparently I introduced another problem. 😢 

@vtjnash, if we can't access shared resources in a finalizer that are protected by a lock, that will be frustrating to work around.  Any ideas?

**Comment by stevengj** [comment]
(Separate from this bug, I wouldn't recommend creating and destroying lots of plans from different threads for performance reasons.  Create your plans once with `plan_fft` and then re-use them in parallel as much as you want.)

**Comment by stevengj** [comment]
I can reproduce the problem: run the following with `JULIA_NUM_THREADS=8`:
```jl
using FFTW
FFTW.set_num_threads(1)
Threads.@threads for i = 1:10000
    a = rand(100)
    fft(a)
    GC.gc()
end
```

**Comment by stevengj** [comment]
@Octogonapus, can you try out #162 and see if it fixes your problem?

**Comment by stevengj** [comment]
FFTW 1.2.4 should be merged soon and includes the fix (https://github.com/JuliaRegistries/General/pull/19855)
