### ISSUE TITLE
Rename the package?

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/FFTW.jl#17]
As we've been finding recently with Iterators.jl vs Base.Iterators and now FFTW.jl vs Base.FFTW, it causes a lot of weird, annoying issues when packages have the same name as a Base module. See for example https://github.com/JuliaMath/FFTW.jl/issues/13 and https://github.com/JuliaStats/Distributions.jl/issues/631. Thus we should probably just follow suit with Iterators and rename the package. While it's unfortunate to lose the name FFTW, I'm not sure it can be helped in this case. Name proposals? cc @stevengj and @tkelman

**Comment by giordano** [comment]
LibFFTW?

**Comment by ararslan** [comment]
That's a very good suggestion, thanks @giordano. Barring strong opposition and/or some better suggestion, I think we should go with that.

**Comment by juliohm** [comment]
I appreciate if this suggestion can be implemented in the next few days. I can't proceed with my work because of this precompilation issue. I hope that by renaming the issue will be gone.

**Comment by stevengj** [comment]
Makes it hard to port code that used things like `FFTW.PATIENT` etcetera.

We are going to run into this issue a lot as we move things out of Base.   It seems like it would be better to find a solution that doesn't require a rename, even if it means changes to Julia itself.

**Comment by stevengj** [comment]
Didn't the Dates.jl package already solve this problem (in the reverse direction, since it was for a package *added* to Base)?

**Comment by tkelman** [comment]
I believe Dates was only used outside of Base before precompilation happened. See the Base issue, Jeff says importing to something other than Main is the long term fix.

**Comment by tkelman** [comment]
I hope `const FFTW = LibFFTW` could make the porting simpler - the problem is what name within Main the modules get resolved and precompiled to.

**Comment by ararslan** [comment]
A better, more robust solution that can happen within Julia for 0.7 would be ideal, but we're still in the same situation for 0.6 that Julio and Tim have run into.

Wouldn't defining `const FFTW = LibFFTW` cause that error that's like "both LibFFTW and Base export FFTW, uses in module Main must be qualified" (or something like that)?

**Comment by tkelman** [comment]
not if it isn't re exported? what doesn't work about it?

**Comment by ararslan** [comment]
```
julia> module LibFFTW
       const FFTW = LibFFTW
       end
LibFFTW

julia> using LibFFTW

julia> using LibFFTW: FFTW

julia> FFTW
Base.DFT.FFTW

julia> import LibFFTW.FFTW
WARNING: ignoring conflicting import of LibFFTW.FFTW into Main

julia> FFTW
Base.DFT.FFTW
```

**Comment by ararslan** [comment]
Since we have no viable solution for 0.6, I still think we should just rename the package. Once a solution in Base is found perhaps it can be backported to 0.6.1 as a bugfix or whatever, but we're in the same boat until then. If everyone can agree that renaming to LibFFTW is a reasonable solution, I'll go ahead with that and submit a PR to Base to adjust the deprecation to recommend LibFFTW instead, and adjust the docs here accordingly. Luckily `FFTW.PATIENT` to `LibFFTW.PATIENT` is a pretty simple find-and-replace for users porting their code.

**Comment by giordano** [comment]
I guess that using this package only in Julia 0.7 isn't an option, right?

**Comment by ararslan** [comment]
We have the same problem in 0.7, since FFTW is still defined in Base as part of the deprecation. The soonest we'd have no trace of FFTW in Base is in 1.0.

**Comment by giordano** [comment]
And renaming the base module to `LibFFTW` with an added `const FFTW = LibFFTW` which preserves deprecations?  I'm just trying to find possible solutions to avoid renaming the package :-)

**Comment by ararslan** [comment]
That wouldn't work for 0.6, where the name in Base is FFTW

**Comment by stevengj** [comment]
Wouldn't `eval(Main, :(const FFTW = LibFFTW))` work?

**Comment by ararslan** [comment]
In what context?

**Comment by ararslan** [comment]
I think that would work okay for end-user code, but couldn't that end up doing weird things inside of packages?

**Comment by stevengj** [comment]
You could stick that line at the end of the module file, guarded by version checks as necessary

**Comment by ararslan** [comment]
Okay, so the plan should be:

1. Rename the package to LibFFTW
2. Add `VERSION >= v"0.7.0-DEV.602" && eval(Main, :(const FFTW = LibFFTW))` in src/LibFFTW.jl
3. Update the Base deprecation messages to point to LibFFTW.jl
4. Submit PRs to all of the packages which depend on FFTW (currently just DSP and Distributions, I think?) to s/FFTW/LibFFTW/g
5. Profit?

**Comment by juliohm** [comment]
@ararslan, the list of dependent packages as of today:

```julia
julia> Pkg.dependents("FFTW")
3-element Array{AbstractString,1}:
 "Distributions"
 "WORLD"        
 "DSP"
```

**Comment by ararslan** [comment]
Thanks @juliohm. Though I realized that since Distributions depends on it, the effective number of packages which depend on it is _much_ larger, since Distributions is a widespread dependency.

**Comment by giordano** [comment]
I have a couple of packages requiring FFTW.jl (not in tagged versions, though), I can update them when necessary

**Comment by ararslan** [comment]
I don't think `eval(Main, :(const FFTW = LibFFTW))` will work for packages that depend on this.
```
julia> module LibFFTW
       eval(Main, :(const FFTW = LibFFTW))
       end
LibFFTW

julia> module A
       using LibFFTW
       println(FFTW)
       end
Base.DFT.FFTW
A
```

**Comment by JeffBezanson** [comment]
`LibFFTW` is an ok name but I don't think a deprecation warning is worth all of this fuss. We can just take out the deprecation. The failure mode is pretty obvious anyway; if you get errors about FFTW or fft not being defined, you install the FFTW package.

**Comment by tkelman** [comment]
I don't think that's self evident at all.

**Comment by ararslan** [comment]
I agree with Tony; if `UndefVarError`s are self-evident, why deprecate anything at all? It's not the deprecation warning that's causing fuss, it's loading issues due to a naming conflict with Base, hence the suggestion to rename.

**Comment by ararslan** [comment]
Anyway, renaming to LibFFTW should just fix everything, then we don't have to fuss about it anymore. And we'll know next time not to name a new package after a Base module.

**Comment by JeffBezanson** [comment]
> deprecation warning that's causing fuss, it's loading issues due to a naming conflict with Base

But that name conflict only exists to provide a deprecation warning...

Are we going to be stuck with LibFFTW as the name forever, or will we name it back? I don't think we want to start putting the `Lib` prefix on various package names.

**Comment by tkelman** [comment]
Given FFTW.jl is registered already and a few things are already depending on it, we'll need to leave it there. We could accomplish a rename in one of two ways, either making a new copy of the package (maybe leave it a fork to make porting things back and forth easier?) or via a repo rename. After 0.7 when the deprecation has served its purpose and it no longer causes precompilation name collision problems we could name it back if desired.

Another possibility is leaving the deprecation in place but not in a 100%-faithful recreation of the 0.6-and-older module structure. Just export deprecated methods from Base that give the migration error, but not export or try to recreate the FFTW module structure within Base. So some code that was referring to the FFTW module by name would break in non-obvious UndefVarError ways that should be fixable with a `using FFTW` referring to the package. Code that was only using exported-from-base fft methods would still get a useful error telling where those functions moved to.

**Comment by giordano** [comment]
Would an empty package do the trick for supporting Julia 0.6?

**Comment by ararslan** [comment]
No, because it's not about the contents of the package, it's about how Julia resolves the name

**Comment by stevengj** [comment]
I just tried creating a `~/.julia/v0.6/FFTW/src/FFTW.jl` file that contains only `import Base.FFTW`, and it seems to work fine in 0.6: `using FFTW` succeeds without error.

**Comment by simonster** [comment]
@stevengj That works great without precompilation, but IIRC it doesn't interact well with precompilation.

**Comment by stevengj** [comment]
@simonster, what's the problem that arises with precompilation? In my suggestion, it doesn't precompile at all in 0.6, only in 0.7, since the `__precompile__(true)` call is inside the version check.

**Comment by stevengj** [comment]
My suggestion seems to be passing all the tests in #21.
