### ISSUE TITLE
Missing symbol in FFTW_jll: FFTW_jll's version numbers are inaccurate

### ISSUE THREAD

**Issue by galenlynch** [JuliaMath/FFTW.jl#170]
As the title says, this is an issue with FFTW_jll, not FFTW. However, issues seem to be locked for FFTW_jll, so I will post my issue here instead.

I am trying to use `fftw_planner_nthreads`, a [new function released with fftw 3.3.9](https://github.com/FFTW/fftw3/blob/34082eb5d6ed7dc9436915df69f376c06fc39762/NEWS#L3), so I can add its functionality to FFTW.jl. However, that symbol does not appear to be in the `.so` artifact shipped with FFTW_jll, which I determined by running `nm` (and `strings`) on the artifact path (which I got with `FFTW_jll.get_libfftw3_path()`). I have confirmed that my FFTW_jll version is `v3.3.9+6`.

I was a bit confused by this. If I build fftw 3.3.9 locally with `--enable-threads --with-combined-threads`, then the `fftw_planner_nthreads` symbol is in the resultant library. If I use the same flags and environment variables as the [`build_tarballs.jl`](https://github.com/JuliaPackaging/Yggdrasil/blob/b6aac212b724b3b1208f286d3cfc66b43ccdff25/F/FFTW/build_tarballs.jl) script that generates FFTW_jll's artifacts, then I also see the `fftw_planner_nthreads` symbol.

I think this boils down to FFTW_jll's version numbers not being the same as fftw's version numbers. While fftw just released version 3.3.9 [six days ago](https://github.com/FFTW/fftw3/issues/210#issuecomment-744092703), FFTW_jll has [already been on version 3.3.9 for more than a year](https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/commit/c13f8d0e2982378f64738c01ce144f0edbf8f8b3). Indeed, if I use the download link for FFTW_jll (http://fftw.org/~stevenj/fftw-3.3.9.tar.gz) instead of the official release (http://fftw.org/fftw-3.3.9.tar.gz) and build it locally, it does not have the function `fftw_planner_nthreads` which was [merged into fftw](https://github.com/FFTW/fftw3/commit/16164a7bf3257376f22ddeda0842805d1c456b01) on August 20 of this year, meaning it is likely quite an old snapshot of fftw's codebase. Perhaps this was a pre-release version that somehow made it into the FFTW_jll artifact stream.

I think this problem would be solved if FFTW_jll's source was the official fftw release, instead of its current stale download link. I also think FFTW_jll's versions should be tied to fftw's, and only released versions should be shipped.

**Comment by giordano** [comment]
Note that in the future `_jll` packages won't follow upstream version numbers because it just doesn't work.

**Comment by galenlynch** [comment]
Oh interesting, so maybe this is just an issue because the numbers are close but not quite the same.

Why does following upstream package version numbers not work?

**Comment by galenlynch** [comment]
Regardless of version numbers, could we please have a new release for fftw 3.3.9 then? Thank you in advance!

**Comment by galenlynch** [comment]
Also curious about how `_jll` packages will work if their version numbers are divorced from the upstream version numbers. Will there be an obvious way to determine the version of the underlying library? I supposed I could see that there would be problems with 1:1 version numbers if some wrapped libraries don't use semver, or if you want to change the Julia portion of a `_jll` package's interface in a breaking way. But I also think most people will want to know the version of the artifact, more than the version of a `_jll` package.

**Comment by giordano** [comment]
I'm a bit confused about what you're asking?  A new version of `FFTW_jll`?  Just do it, edit [this file](https://github.com/JuliaPackaging/Yggdrasil/blob/b6aac212b724b3b1208f286d3cfc66b43ccdff25/F/FFTW/build_tarballs.jl) as appropriate

**Comment by giordano** [comment]
> I supposed I could see that there would be problems with 1:1 version numbers if some wrapped libraries don't use semver, or if you want to change the Julia portion of a `_jll` package's interface in a breaking way.

That's exactly the problem.

> But I also think most people will want to know the version of the artifact, more than the version of a `_jll` package.

That's why so far we followed the upstream version.

**Comment by galenlynch** [comment]
Ok, I just made a PR to Yggdrasil with my proposed change: use the official release for fftw 3.3.9, instead of the code at the old link which may be an older pre-release version of 3.3.9.

**Comment by galenlynch** [comment]
Closed by  JuliaPackaging/Yggdrasil#2291.
