### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/FFTW.jl#18]
There seems to be some issue with BinDeps on Windows such that `BinDeps.debug("FFTW")` shows no available providers for `libfftw` and `libfftwf` on Windows. So this package is effectively unusable on Windows with Julia 0.7.

**Comment by ViralBShah** [comment]
Cc @staticfloat (if this is useful for new BinDeps work)

**Comment by ararslan** [comment]
As it turns out, this appears to be human error. I assumed the WinRPM provider expected a name that matched one listed on the openSUSE build service website, so I specified `fftw3` to match `mingw64-fftw3`. But playing around within WinRPM directly, it apparently doesn't know what `fftw3` is:
```
julia> WinRPM.search("fft")
WinRPM Package Set:
  1. fftw3-debug (mingw64) - Debug information for package mingw64-fftw3
  2. fftw3-debugsource (mingw64) - Debug sources for package mingw64-fftw3
  3. fftw3-devel (mingw64) - Include Files and Libraries mandatory for Development
  4. libfftw3-3 (mingw64) - Discrete Fourier Transform (DFT) C Subroutine Library
```
Updating to `libfftw3-3` seems to have fixed it (ref https://github.com/JuliaMath/FFTW.jl/pull/19), but it's hard to know for sure because of https://github.com/JuliaLang/julia/issues/22431 and https://github.com/JuliaLang/julia/issues/22668.

**Comment by musm** [comment]
I think this is now fixed
