### ISSUE TITLE
Docs stop being deployed?

### ISSUE THREAD

**Issue by navidcy** [JuliaMath/FFTW.jl#185]
In the Documentation I can't seem to be able to find the docs for the latest releases, e.g. v1 and later on.

<img width="380" alt="Screen Shot 2021-03-12 at 9 34 09 am" src="https://user-images.githubusercontent.com/7112768/110864407-2d739200-8316-11eb-9a8e-3f59de96aaee.png">

Have the docs stopped being build/deployed?

This line
```Julia
┌ Warning: removing `stable` and linking `stable` to `v0.2.4`.
158
└ @ Documenter ~/.julia/packages/Documenter/FuXcO/src/Documenter.jl:683
159
```
from the `julia-docdeploy` section in GitHub Actions log at https://github.com/JuliaMath/FFTW.jl/runs/1882720951?check_suite_focus=true#step:6:157 is a bit puzzling... Why linking to v0.2.4?

**Comment by giordano** [comment]
Documentation for v1.3.2 is now available: https://juliamath.github.io/FFTW.jl/v1.3.2/.  The problems with Documenter setup were already fixed by #179.
