### ISSUE TITLE
Could not load symbol "fftw_init_threads"

### ISSUE THREAD

**Issue by Clonkk** [JuliaMath/FFTW.jl#196]
When tyring to initialize FFTW.jl from C (using Julia C-API) I get an error that I symbols from ``libfftw3_threads.so`` are missing.

Full error : 
```
Error: unhandled exception: InitError: could not load symbol "fftw_init_threads":
/usr/lib64/libfftw3.so: undefined symbol: fftw_init_threads
during initialization of module FFTW [JlError]
```

Is there a threading parameter to use when calling FFTW.jl from C ? 
Note that I have passed -DJULIA_ENABLE_THREADING=1 on compilation.

**Comment by Clonkk** [comment]
So my build system is a bit specific. 
To get into details : I made a bridge between the programming language Nim and Julia using the C-API of Julia (there are unit tests so I'm relatively confident that the generated C code is correct).
Nim code is compiled code to C and then calls gcc. 

``libfftw3.so `` and ``libfftw3_threads.so`` are both in ``/usr/lib64/`` and have been installed through the package manager zypper (I use OpenSUSE).

I tried linking explicitly  ``-lfftw3_threads -lfftw3`` but calling FFTW.jl from native code still didn't work. 

On the other hand, If I use FFTW C API, compiled with ``-lfftw3_threads -lfftw3`, fftw (C versions) work without issue.

**Comment by giordano** [comment]
Well, you need to link to a version of FFTW matching the one used by this package, namely v3.3.9.  You can also link to the library shipped by `FFTW.jl`, its path is in `FFTW_jll.libfftw3_path`

**Comment by Clonkk** [comment]
I reinstalled my system library from source (http://www.fftw.org/fftw-3.3.9.tar.gz).

I checked with ``ldd``, my binary is linked against ``libfftw3.so.3.6.9`` and ``libfftw3_threads.so.3.6.9`` - 3.6.9 being the version of the .so file inside the archive 3.3.9 (no idea why). 

I still have the same error :) .

**Comment by giordano** [comment]
Can you run
```
nm /path/to/libfftw3.so.3.6.9 | grep fftw_init_threads
```?

**Comment by Clonkk** [comment]
Do you mean ``nm /usr/local/lib64/libfftw3_threads.so.3.6.9 | grep fftw_init_threads`` as fftw_init_threads is not ``libfftw3.so`` but in ``libfftw3_threads.so`` ?

```
nm /usr/lib64/libfftw3_threads.so.3 | grep fftw_init_threads
0000000000004e50 T dfftw_init_threads_
0000000000004e90 T dfftw_init_threads__
0000000000002350 T fftw_init_threads
```

**Comment by giordano** [comment]
No, I literally meant what I said, because that's where `fftw_init_threads` in the FFTW library shipped by `FFTW.jl`:
```julia
julia> filter(l -> occursin("fftw_init_threads", l), split(readchomp(`nm $(FFTW_jll.libfftw3_path)`), '\n'))
1-element Vector{SubString{String}}:
 "0000000000220b00 T fftw_init_threads"
```

**Comment by Clonkk** [comment]
There is no match for ``nm /usr/lib64/libfftw3.so.3 | grep fftw_init_threads``

Do you load the symbol through ``dlopen()`` ? The binary generated from FFTW archive have ``fftw_init_threads`` in ``libfftw3_threads.so``

**Comment by giordano** [comment]
We [build FFTW](https://github.com/JuliaPackaging/Yggdrasil/blob/5e7932c3c0d0ba56794b1352b6325e5fe2145606/F/FFTW/build_tarballs.jl#L27) with `--with-combined-threads`.  Quoting from the [documentation](http://www.fftw.org/fftw3_doc/Installation-on-Unix.html)

>  `--with-combined-threads`: By default, if `--enable-threads` is used, the threads support is compiled into a separate library that must be linked in addition to the main FFTW library. This is so that users of the serial library do not need to link the system threads libraries. If `--with-combined-threads` is specified, however, then no separate threads library is created, and threads are included in the main FFTW library. This is mainly useful under Windows, where no system threads library is required and inter-library dependencies are problematic.

**Comment by Clonkk** [comment]
Ah okay I used ``--enable-thread --enable-shared`` I'll rebuild the library and check

**Comment by Clonkk** [comment]
``--with-combined-threads`` was the root of the issue ! 

Thank you for your help
