### ISSUE TITLE
Problem with `FFTW=1.4.3` ignoring `DEPOT_PATH` variable at runtime

### ISSUE THREAD

**Issue by theweaklink** [JuliaMath/FFTW.jl#208]
hi there,

we have noticed a problem on our end with FFTW `1.4.3` which seems to ignore the env variable `JULIA_DEPOT_PATH` (internally in Julia `DEPOT_PATH`) when loading the library.

We have been building an image with `PkgCompiler`: in our build environment (clean Docker image), the depot path is `/build_jl/depot`.
With FFTW `1.4.2` and `1.4.1` we havent had any issue loading the library as we are setting the env var `JULIA_DEPOT_PATH` (e.g. `/my/new/depot`) before loading the library and it has been working fine so far.
However, since `1.4.3`, setting the env var `JULIA_DEPOT_PATH` doesn't do anything and we get the error:
```
InitError(mod=:FFTW, error=ErrorException("could not load library "/build_jl/depot/artifacts/81791030d1dcd08bf0c67b3e8224cb573d0f5a0a/lib/libfftw3.so"
```

clearly pointing to the `JULIA_DEPOT_PATH` set at build time and not at runtime.

It seems that the PR #207 was the only change between `1.4.2` and `1.4.3` but I can't pinpoint more than that (sorry!).
Is that actually possible to make the #207 compatible with specifying the `JULIA_DEPOT_PATH` at runtime?

cheers

**Comment by KristofferC** [comment]
I think this should be fixed in the new release.

**Comment by theweaklink** [comment]
Sounds good, thanks for the follow up, I'll check once the release comes out and let you know.
cheers

**Comment by KristofferC** [comment]
The release should already be out.

**Comment by theweaklink** [comment]
Indeed, my bad for the release.
I just checked with FFTW 1.4.5 and it works like a charm, there is no longer an issue. Thanks very much for the fix!
cheers
