### ISSUE TITLE
First call to plan_rfft trashes the input

### ISSUE THREAD

**Issue by jaakkor2** [JuliaMath/FFTW.jl#226]
On a fresh new session on official release of Julia v1.7.1 on Windows 10 with `FFTW.version` giving `v"3.3.10"`
```
using FFTW
A = ones(18);
p = plan_rfft(A, flags = FFTW.MEASURE);
A
```
outputs
```
18-element Vector{Float64}:
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
```
Vector of length 17 and smaller seem to be fine, lengths 18 and longer seem to be trashed.

Matrix inputs are trashed as well, again on a new session
```
using FFTW
A = ones(18,2)
p = plan_rfft(A, flags = FFTW.MEASURE);
A
```
outputs
```
18×2 Matrix{Float64}:
 0.0  1.0
 0.0  1.0
 0.0  1.0
 ⋮
 0.0  1.0
 0.0  1.0
 0.0  1.0
```

I did not observe trashing when I omitted `flag = FFTW.MEASURE`.

Second call to `plan_rfft` in the same session seem to work fine.

`plan_fft` seemed to be fine.

**Comment by stevengj** [comment]
Yes, this is normal.  FFTW.MEASURE runs several FFTs using the input array to time different algorithms and pick the fastest, which overwrites the input array (and the output array, if any).

**Comment by jaakkor2** [comment]
Weird why this is seen with `plan_rfft`, but not with `plan_fft`.

Could Julia copy the input argument as is done in `plan_bfft` if `PRESERVE_INPUT` flag is not available?
https://github.com/JuliaMath/FFTW.jl/blob/v1.4.5/src/fft.jl#L758-L759

**Comment by jaakkor2** [comment]
Fair enough the behavior is documented 
> Passing FFTW.MEASURE or FFTW.PATIENT may cause the input array A to be overwritten with zeros during plan creation.
