### ISSUE TITLE
Do not import deprecated bindings

### ISSUE THREAD

**Issue by giordano** [JuliaMath/FFTW.jl#23]
Recent CI logs on nightlies show hundreds of spurious warnings because the package imports deprecated bindings, see, e.g., https://travis-ci.org/JuliaMath/FFTW.jl/jobs/254462935#L785  While these messages are going to cleared, they are an indication that after https://github.com/JuliaLang/julia/pull/22763 deprecated bindings shouldn't be imported at all.  An example of fix for `SpecialFunctions.jl` is at https://github.com/JuliaMath/SpecialFunctions.jl/pull/36

**Comment by ararslan** [comment]
I actually think this will be mostly fixed by https://github.com/JuliaMath/AbstractFFTs.jl/pull/6.
