### ISSUE TITLE
r2r for complex number

### ISSUE THREAD

**Issue by Lightup1** [JuliaMath/FFTW.jl#241]
In mathematica:
![image](https://user-images.githubusercontent.com/32999017/168456802-c856f5a0-0494-4376-9694-2c21da86edb7.png)

Is there a way to implement that in FFTW.jl?

**Comment by stevengj** [comment]
Yes, this is already supported.  `FourierDST` in Mathematica corresponds to a type-II DST, which is called `FFTW.RODFT10` in FFTW, with a slightly different normalization:
```jl
julia> dst(x) = FFTW.r2r(x, FFTW.RODFT10) / 2√length(x)
dst (generic function with 1 method)

julia> dst([1,2im,3,4im])
4-element Vector{ComplexF64}:
   1.5771610149494748 + 1.6892463972414662im
  -0.7071067811865476 - 0.7071067811865476im
 -0.11208538229199128 + 1.4650756326574836im
                  2.0 - 3.0im
```

**Comment by Lightup1** [comment]
It is caused by the provider of "mkl".
After I change it back to "fftw", things become normal.
