### ISSUE TITLE
Normalization of FFTW.r2r for FFTW.RODFT00

### ISSUE THREAD

**Issue by almost6heads** [JuliaMath/FFTW.jl#268]
I am confused about the r2r transform with odd symmetry. According to the FFTW manual, if I apply the RODFT00 transform to a unit vector of length 1, the result should be the vector [2]. But in Julia the commands u=ones(1,1) and v = FFTW.r2r(u,FFTW.RODFT00) gives the vector 4. Am I using this routine wrong?

**Comment by stevengj** [comment]
With `ones(1,1)` you have a 2d array, so you did a 2d RODFT00 x RODFT00 transform, which multiplies by 2 twice.  If you want a 1d vector of length 1, use `ones(1)`.
