### ISSUE TITLE
Init error on Mac M2

### ISSUE THREAD

**Issue by mattsignorelli** [JuliaMath/FFTW.jl#290]
Running on Mac arm64, Julia v1.10, here is the full output:
```
﻿﻿julia> using FFTW
ERROR: InitError: could not load symbol "fftw_init_threads":
dlsym(0x85691410, fftw_init_threads): symbol not found
Stacktrace:
  [1] fftw_init_threads
    @ FFTW ~/.julia/packages/FFTW/ToovV/src/providers.jl:69 [inlined]
  [2] __init__()
    @ FFTW ~/.julia/packages/FFTW/ToovV/src/FFTW.jl:32
  [3] run_module_init(mod::Module, i::Int64)
    @ Base ./loading.jl:1128
  [4] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1116
  [5] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
    @ Base ./loading.jl:1061
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base ./loading.jl:1575
  [7] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1932
  [8] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1806
  [9] #invoke_in_world#3
    @ Base ./essentials.jl:921 [inlined]
 [10] invoke_in_world
    @ Base ./essentials.jl:918 [inlined]
 [11] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1797
 [12] macro expansion
    @ Base ./loading.jl:1784 [inlined]
 [13] macro expansion
    @ Base ./lock.jl:267 [inlined]
 [14] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1747
 [15] #invoke_in_world#3
    @ Base ./essentials.jl:921 [inlined]
 [16] invoke_in_world
    @ Base ./essentials.jl:918 [inlined]
 [17] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1740
during initialization of module FFTW
```

**Comment by stevengj** [comment]
Works for me on a fresh install:
```jl
julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 6 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_CXX_RTTI = 1
```

**Comment by giordano** [comment]
What's the output of
```
]st -m
```
?

**Comment by mattsignorelli** [comment]
```
(@v1.10) pkg>  st -m FFTW_jll FFTW
Status `~/.julia/environments/v1.10/Manifest.toml`
  [7a1cc6ca] FFTW v1.7.2
  [f5851436] FFTW_jll v3.3.10+0
```

**Comment by mattsignorelli** [comment]
Here is what I get for grepping for `fftw_init_threads` from an `nm` on `libfftw3.dylib` in the artifact
```
 nm libfftw3.dylib | grep fftw_init_threads
00000000000db1e4 T _dfftw_init_threads_
00000000000db230 T _dfftw_init_threads__
00000000000d8a38 T _fftw_init_threads
```

So it seems like the symbol is there

**Comment by mattsignorelli** [comment]
This is very strange...  I wrote a C code mimicking the Julia and `dlsym` finds a lot of the symbols in FFTW, except it appears all of those involving threads. So that may be a clue

**Comment by mattsignorelli** [comment]
Not sure if it helps but
```
julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 24 × Apple M2 Ultra
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 16 virtual cores
```

**Comment by mattsignorelli** [comment]
I completely deleted Julia, deleted `.julia`, reinstalled, and am getting the same error.

**Comment by mattsignorelli** [comment]
I've narrowed down the problem to the `--with-combined-threads` flag in the compile, which is used in the `build_tarballs.jl`. This flag compiles everything into one library, instead of having a separate `fftw_threads` library to link to (see [https://www.fftw.org/fftw3_doc/Installation-on-Unix.html](https://www.fftw.org/fftw3_doc/Installation-on-Unix.html)). When I don't use this flag, and `dlsym` the symbol `fftw_init_threads` from the separate library generated `libfftw3_threads.dylib`, I can successfully load the symbol into Julia.

**Comment by stevengj** [comment]
Weird that I am running on almost the same arch, with the same Julia and package versions, and I can't reproduce…

**Comment by giordano** [comment]
I also couldn't reproduce on M1.

**Comment by giordano** [comment]
@mattsignorelli what version of macOS are you using?  I think I was on 12.6 (I don't have my macbook at hand right now).

**Comment by mattsignorelli** [comment]
@giordano I'm on 14.2

**Comment by giordano** [comment]
There's probably something weird in macOS 14, other projects had problems as well, for example https://github.com/neovim/neovim/pull/25274 (pointed out by @mkitti). Frankly it looks odd to me that having everything in a single shared library is a problem.

**Comment by xlxs4** [comment]
Couldn't reproduce on fresh environment, M2 Pro, Sonoma 14.3
```julia
julia> using FFTW

julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M2 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 6 virtual cores

(bug) pkg> st -m FFTW_jll FFTW
Status `~/bug/Manifest.toml`
  [7a1cc6ca] FFTW v1.7.2
  [f5851436] FFTW_jll v3.3.10+0
```

**Comment by StefanKarpinski** [comment]
Just as a data point, I'm on MacOS 14.2.1 on an M2 system and I can't repro this using Julia 1.10.0 and the exact same versions of FFTW and FFTW_jll. How did you install Julia?

**Comment by brenhinkeller** [comment]
Looks ok here
```
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.0 (2023-12-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.10) pkg> add FFTW
   Resolving package versions...
    Updating `~/.julia/environments/v1.10/Project.toml`
  [7a1cc6ca] + FFTW v1.7.2
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`

julia> using FFTW

julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

**Comment by mattsignorelli** [comment]
> Just as a data point, I'm on MacOS 14.2.1 on an M2 system and I can't repro this using Julia 1.10.0 and the exact same versions of FFTW and FFTW_jll. How did you install Julia?

I tried with Julia v1.10 from Juliaup installed with the standard `curl` , and also a regular MacOS Julia install.

But right now, I am compiling the library manually outside of Julia (using the same flags in the `build_tarballs.jl` build script) and `dlsym` in even a C program is giving the result above. So for whatever reason `dlsym` itself is having problems finding the symbol unless the `-export_dynamic` flag is explicitly used.

**Comment by mattsignorelli** [comment]
Ah, I have figured it out. There is a separate software in my `.bash_profile` which adds its own FFTW to the `DYLD_LIBRARY_PATH`. Adding to `DYLD_LIBRARY_PATH` instead of `DYLD_FALLBACK_LIBRARY_PATH` can cause [this exact problem](https://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s
). It probably shouldn't be doing this. I modified it to instead add to `DYLD_FALLBACK_LIBRARY_PATH` and now I can do `using FFTW`.

Thanks for everyone's time. If someone else has a similar problem in the future with either FFTW or other common packages, this could be something to check for on Mac.

**Comment by mkitti** [comment]
We should make `versioninfo()` print these environment variables. I thought it did...

**Comment by stevengj** [comment]
It should: https://github.com/JuliaLang/julia/blob/0f7b598ad2a690cae4fe67b3f834e476a77399f4/stdlib/InteractiveUtils/src/InteractiveUtils.jl#L166-L168

@mattsignorelli, did you truncate your `versioninfo()` output above?

**Comment by mattsignorelli** [comment]
Yes, I did
