### ISSUE TITLE
v1.8.0 missing from Releases?

### ISSUE THREAD

**Issue by navidcy** [JuliaMath/FFTW.jl#292]
I see FFTW v1.8.0 at 

https://github.com/JuliaRegistries/General/blob/737c1df2b7882245ce18c73aa1c84340a4cc4089/F/FFTW/Versions.toml#L100-L101

but I can't see anything at https://github.com/JuliaMath/FFTW.jl/releases or https://github.com/JuliaMath/FFTW.jl/tags

I think there is a problem with TagBot. See, e.g., https://github.com/JuliaMath/FFTW.jl/actions/runs/7603519915/job/20705363542#step:3:43

**Comment by ViralBShah** [comment]
Yes there has been a problem with tagbot in the past. It's good nowadays.
