### ISSUE TITLE
Failled to create a usable precompiled cache file

### ISSUE THREAD

**Issue by juliohm** [JuliaMath/FFTW.jl#45]
Today when I loaded Images.jl, I got the following warning regarding FFTW.jl:

```julia
INFO: Recompiling stale cache file /home/juliohm/.julia/lib/v0.6/Images.ji for module Images.
WARNING: --output requested, but no modules defined during run
WARNING: The call to compilecache failed to create a usable precompiled cache file for module FFTW. Got:
WARNING: Cache file "/home/juliohm/.julia/lib/v0.6/FFTW.ji" not found.
WARNING: eval from module Main to FFTViews:    
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/home/juliohm/.julia/v0.6/FFTW/src/FFTW.jl")::Any
  ** incremental compilation may be broken for this module **
```

I tried testing the package, and all tests are passing. What this warning is referring to? Is it still related to that issue of naming conflict in Base?

**Comment by ararslan** [comment]
What's your `Pkg.status("FFTW")`?

**Comment by juliohm** [comment]
I am using FFTW v0.0.4

**Comment by ararslan** [comment]
Can you run `Pkg.update()` and try again? That version is rather old.

**Comment by juliohm** [comment]
Oh interesting, some other package must be holding me back. I did update this morning. Tried again and it still pulling 0.0.4.

**Comment by juliohm** [comment]
Any way to discover the package that is holding the version?

**Comment by ararslan** [comment]
Hm. I don't think any package has upper bounded FFTW. I checked with this, which returns no results for me:
```julia
for (root, dirs, files) in walkdir(Pkg.dir("METADATA")), file in files
    file == "requires" || continue
    any(s->startswith(s, "FFTW "), eachline(joinpath(root, file))) && println(root)
end
```
Note the trailing space after FFTW; this will ensure we only match lines that have some kind of bound—upper or lower—on FFTW.

Try explicitly updating FFTW with `Pkg.update("FFTW")`.

**Comment by juliohm** [comment]
Tried updating it explicitly, still 0.0.4. Do you think this is related to that naming conflict again?

**Comment by ararslan** [comment]
No, that shouldn't affect package management.

When you do `Pkg.status()`, is FFTW listed in the "required packages" or "additional packages" section? If it's only installed because it's a dependency of another package you have installed, you may need to explicitly install it, i.e. `Pkg.add("FFTW")`, then try updating again.

**Comment by juliohm** [comment]
I don't think it makes any difference, also, I would expect the manager to update all packages (required or additional) when new versions are released.

I just tried adding it to the required packages with Pkg.add() and then Pkd.update("FFTW"), it still points to 0.0.4

**Comment by juliohm** [comment]
Oh, wait, I am on Julia v0.6! FFTW 0.0.4 is the latest supported version.

**Comment by juliohm** [comment]
I will close this issue for now as it is not affecting my usage so far. If something else pops up, I open another one. Thank you for your prompt replies!

**Comment by ararslan** [comment]
Oh that's right, I forgot that I dropped 0.6 support a while back. Unfortunately I'm really not sure how to improve the situation on 0.6. Any precompiled module that depends on FFTW will look for the compiled cache for FFTW and won't find it since on 0.6 it's just calling the functions from Base. The solution would be for packages that depend on FFTW to disallow module precompilation on 0.6, but that kind of sucks.

**Comment by jingpengw** [comment]
this prevents my docker auto build, can we reopen this issue?

**Comment by jingpengw** [comment]
I see, this was split out from the Base in julia 0.7

**Comment by ararslan** [comment]
If you're using only Julia 0.6 on Docker, don't bother adding the FFTW package, as that will produce a warning. Just use Base.FFTW. However, if you're doing both 0.6 and 0.7, you'll need to add the package.
