### ISSUE TITLE
Typo in a `plan_inv` method

### ISSUE THREAD

**Issue by martinholters** [JuliaMath/FFTW.jl#59]
Reported by @appleparan in https://github.com/JuliaLang/julia/issues/25598:
https://github.com/JuliaMath/FFTW.jl/blob/6e26a1ee12c5f05a9c8eb5f653b56f04ab568b80/src/fft.jl#L700

**Comment by appleparan** [comment]
OMG. I thought this statement was removed on FFTW.jl. Thanks.
