### ISSUE TITLE
precompilation error

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaMath/FFTW.jl#61]
Hi I am getting this
```
WARNING: --output requested, but no modules defined during run
WARNING: The call to compilecache failed to create a usable precompiled cache file for module FFTW. Got:
WARNING: Cache file "/home/febbo/.julia/lib/v0.6/FFTW.ji" not found.
WARNING: eval from module Main to FFTViews:    
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/home/febbo/.julia/v0.6/FFTW/src/FFTW.jl")::Any
  ** incremental compilation may be broken for this module **
```

Any ideas on how to fix this?

Thanks!

**Comment by appleparan** [comment]
First of all, on Julia v0.6, it uses `Base.FFTW`. You can just use `Base.FFTW` rather than install `FFTW.jl`.
Second, it seems `/home/febbo/.julia/lib/v0.6/FFTW.ji` doesn't exists, would you remove and reinstall `FFTW` again?

**Comment by ararslan** [comment]
Known issue, unavoidable on 0.6. See https://github.com/JuliaMath/FFTW.jl/issues/46. Note that these are warnings, not errors, and everything will still work as intended.
