### ISSUE TITLE
FFTW planner is not thread safe.

### ISSUE THREAD

**Issue by KristofferC** [JuliaMath/FFTW.jl#66]
Moved from https://github.com/JuliaLang/julia/issues/17972

---------------------

Having fft/bfft/ifft/etc. calls in a threaded region exposes the fact that the planning portion of the fft call is not thread-safe in fftw.  Below is a potential patch to dft.jl if you just want to lock the planner.

```
global planner_mutex = nothing

function __init__()
    global planner_mutex = Base.Threads.Mutex()
end

# implementations only need to provide plan_X(x, region)
# for X in (:fft, :bfft, ...):
for f in (:fft, :bfft, :ifft, :fft!, :bfft!, :ifft!, :rfft)
    pf = Symbol("plan_", f)
    @eval begin
        function $f(x::AbstractArray)
            Base.Threads.lock!(planner_mutex)
            the_plan = $pf(x)
            Base.Threads.unlock!(planner_mutex)
            the_plan * x
        end
        function $f(x::AbstractArray, region)
            Base.Threads.lock!(planner_mutex)
            the_plan = $pf(x, region)
            Base.Threads.unlock!(planner_mutex)
            the_plan * x
        end
        function $pf(x::AbstractArray; kws...)
            Base.Threads.lock!(planner_mutex)
            the_plan = $pf(x, 1:ndims(x); kws...)
            Base.Threads.unlock!(planner_mutex)
            the_plan
        end
    end
end
```

**Comment by stevengj** [comment]
You could call [fftw_make_planner_thread_safe](http://fftw.org/fftw3_doc/Thread-safety.html#index-fftw_005fmake_005fplanner_005fthread_005fsafe) instead, although it basically does the same thing.

If you are implementing locks, note that you also need to put a lock around the `fftw_destroy_plan` call.
