### ISSUE TITLE
Migrate the build to BinaryBuilder

### ISSUE THREAD

**Issue by ViralBShah** [JuliaMath/FFTW.jl#73]
Is there any effort to migrating the build to BinaryBuilder?

**Comment by stevengj** [comment]
Should be straightforward.  The FFTW build system already supports cross-compiling (and we've used cross-compiling to generate Windows binaries for many years).

**Comment by ararslan** [comment]
I looked into this the other day but ran into issues with the BinaryBuilder wizard. I'll try again soon.

**Comment by ararslan** [comment]
For reference, this currently uses https://github.com/ararslan/fftw-builder, which predates BinaryBuilder's maturity and can now simply be repurposed to use BinaryBuilder.

**Comment by ViralBShah** [comment]
I guess if you use the wizard, then it will want to do its own thing. But maybe the simplest thing is to let the wizard create its own thing, and then edit `build_tarballs.jl` with the relevant stuff from fftw-builder.

**Comment by ViralBShah** [comment]
Maybe if there is a new package, it can be called FFTWBuilder to be consistent with the other builders, although that is not important in any way.

**Comment by stevengj** [comment]
I gave up on using the wizard a while back and ended up just writing `build_tarballs.jl` myself.  (Actually, `build_tarballs.jl` is the easy part, given a couple of examples.  I eventually figured out that getting the OAuth token yourself is most easily done via `travis setup releases`, as explained [here](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/master/docs/src/index.md#project-flow).)

**Comment by ararslan** [comment]
@stevengj If you want to take on writing that file for FFTW, I'd happily accept it as a PR on fftw-builder. I can also rename the repo to FFTWBuilder. Alternatively we can make a new repo, I'm fine with whatever.

**Comment by stevengj** [comment]
I think you may have to generate the OAuth token yourself since you own the repo?

**Comment by ViralBShah** [comment]
Maybe make a new repo in JuliaMath?

**Comment by stevengj** [comment]
I'll look into it.

**Comment by ararslan** [comment]
> I think you may have to generate the OAuth token yourself since you own the repo?

I already have an auth token that the repo uses now.

**Comment by stevengj** [comment]
I just created https://github.com/JuliaMath/FFTWBuilder with a first draft of the build script.  It's building now, so let's see what happens.

**Comment by ViralBShah** [comment]
Seems like it couldn't find configure.

**Comment by stevengj** [comment]
Seems to be mostly working now except for FFTW/fftw3#146 ... a workaround would be to simply not build the `fftwf-wisdom` tool, since we don't need that anyway.

**Comment by stevengj** [comment]
Okay, the build is now available at https://github.com/JuliaMath/FFTWBuilder/releases/tag/v3.3.8

Note that I compiled `--with-combined-threads` on every platform, so there is no separate `libfftw3_threads` library.   I didn't build with threads on FreeBSD because of https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/232.
