### ISSUE TITLE
How can I transform of 2D FFT for image? 

### ISSUE THREAD

**Issue by bemoregt** [JuliaMath/FFTW.jl#93]
Hi, @jiahao @wildart @antoine-levitt @staticfloat @mortenpi 

How can I transform of 2D FFT for image using Julia(FFTW)? 

I wonder.

Thanks.

**Comment by staticfloat** [comment]
Please read [the documentation](https://juliamath.github.io/FFTW.jl/stable/) of the package, you will find the answer in there.  If you have a specific question about usage of a particular function, or you think the docs could be made clearer in some way, you are welcome to open an issue about it, but in general please do not ping a bunch of people asking a question that can be answered by reading the docs.  GitHub issues are not the right place to ask general usage questions, I suggest you try the [JuliaLang discourse](https://discourse.julialang.org) or the slack channel in the future, especially as there are many more readers of discourse and slack than there are readers of this github repository.
